export { default as const_level } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-level.vue';
export { default as const_isClose } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-isclose.vue';
export { default as const_closeTime } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-closetime.vue';
export { default as const_alertTime } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-alerttime.vue';
export { default as const_updateTime } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-updatetime.vue';
export { default as const_type } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-type.vue';
export { default as const_title } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-title.vue';
export { default as const_status } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-status.vue';
export { default as const_userList } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-userlist.vue';
export { default as const_teamList } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-teamlist.vue';
export { default as const_source } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-source.vue';
export { default as const_markList } from '@/community-module/alert/pages/alert/alert-attr/alertattr-const-markList.vue';
//自定义属性是根据类型分类
export { default as attr_text } from '@/community-module/alert/pages/alert/alert-attr/alertattr-attr-text.vue';
export { default as attr_number } from '@/community-module/alert/pages/alert/alert-attr/alertattr-attr-number.vue';
export { default as attr_datetime } from '@/community-module/alert/pages/alert/alert-attr/alertattr-attr-datetime.vue';
export { default as attr_html } from '@/community-module/alert/pages/alert/alert-attr/alertattr-attr-html.vue';
export { default as attr_json } from '@/community-module/alert/pages/alert/alert-attr/alertattr-attr-json.vue';
export { default as attr_csv } from '@/community-module/alert/pages/alert/alert-attr/alertattr-attr-csv.vue';
